### ISSUE TITLE
서브페이지 콘솔 오류 관련 문제

### ISSUE THREAD

**Issue by PronCan** [Team9896/Project-Trip#68]
subpage => 튀르키예 부분에서 section01의 swiper '수멜라 수도원' 넘어가는 부분에서 해당 에러가 발생합니다

undefined:1          GET http://127.0.0.1:5500/subPage/undefined 404 (Not Found)
![image](https://user-images.githubusercontent.com/17294545/211108749-f6d9ddfd-1c5f-41b2-9023-5df5eccb937b.png)

해당 문제 확인 필요한것으로 보임 ㅇㅁㅇ

**Comment by khj0196** [comment]
json에 이미지 추가 함으로 해결완료
