### ISSUE TITLE
서브페이지 베트남 이미지 오류 

### ISSUE THREAD

**Issue by PronCan** [Team9896/Project-Trip#69]
![image](https://user-images.githubusercontent.com/17294545/211109613-f0299d41-b51a-4e4c-8d1e-8cc595a9610c.png)
![image](https://user-images.githubusercontent.com/17294545/211109631-0667c94f-694d-4b3b-9843-be00a95f8b2b.png)

베트남 2번째 '호이안' 에서 이미지 불러오지 못하는 오류 있음

**Comment by PronCan** [comment]
아마 다른 이미지들은 01, 02, 03 순으로 시작하는데
이 페이지는 '', 01, 02 순으로 시작해서 그런게 아닐까 싶음(추측, 자세하게는 확인 안해봄...)

**Comment by khj0196** [comment]
파일명 변경으로 해결완료
